### ISSUE TITLE
automate puiblishing new versions

### ISSUE THREAD

**Issue by DetachHead** [ducdetronquito/pybun#1]
the current version of bun is 1.1.29, and the latest version on pypi is 1.1.25. it would be nice if there was a github action that checks for a new version every day or something and automatically publishes a new release when needed.

an example of a similar project that does this is https://github.com/breuerfelix/chromedriver-py

**Comment by ducdetronquito** [comment]
Hi @DetachHead !

Wow I did not expect anyone to use pybun but I'm glad you gave it a try :)

This makes perfect sens but I had not clue on how to do it, so thanks for the advice about chromedriver-py !

I can't promise any deadlines, but I hope to do it this week thanks to the shitty weather :D

I keep you in touch when I have something working.

Have a nice day !

**Comment by DetachHead** [comment]
no rush! thanks for the quick reply and for making pybun

i wish pypi wrapper projects like this were more popular, it makes projects that depend on different tools so much easier to manage

**Comment by ducdetronquito** [comment]
Hello @DetachHead !

I've made a new github action workflow to automate release following your work on chromedriver-py !

It should run at midnight and release Bun v1.1.30 if I did not messed up somewhere :)

**Comment by ducdetronquito** [comment]
Well I was to eager to test it so I just ran the process manually this time and everything works :tada: 

Thanks again for the nice inputs :)
