### ISSUE TITLE
separate package for only the binaries without the CLI

### ISSUE THREAD

**Issue by DetachHead** [ducdetronquito/pybun#2]
if i'm publishing a package that depends on bun, i don't want the CLI to be available because i don't want the user to unknowingly have a `bun` executable added to their PATH. instead i only want the binaries to be accessible programmatically.

for example the [nodejs-wheel](https://github.com/njzjz/nodejs-wheel?tab=readme-ov-file#unoffical-nodejs-wheels) project publishes  separate `nodejs-wheel-binaries` and `nodejs-wheel` packages (https://github.com/njzjz/nodejs-wheel/issues/23)

**Comment by ducdetronquito** [comment]
Hi again @DetachHead !

Thanks for your feedback, I will look into it too !
